# Generated by Django 2.0 on 2018-09-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20180829_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='genericexpense',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
